integrating userlist from graphql
indigotech/onboard-silas-lima pull request #16
Opened 2022-09-12 14:28 UTC by silas-lima

Track 5 - Step 2

2022-09-12 15:47 UTC, Educ71 approved these changes

2022-09-12 17:25 UTC, alanraso requested changes

2022-09-12 17:25 UTC, alanraso commented on pages/users-page.tsx
> +  function UsersQuery() {
Funções locais a gente nomeia com `camelCase` mesmo

2022-09-12 17:25 UTC, alanraso commented on pages/users-page.tsx
> +
Acho que não é uma boa criar esse componente dentro do `UsersPage`. Eu nem sei como isso se comportaria na teora, mas eu tenho impressão que ele remontaria o componente a cada render da página, o que faria com que ele fizesse a chamada algumas vezes a mais desnecessariamente.

2022-09-12 18:03 UTC, silas-lima commented on pages/users-page.tsx
> +
Demorei para entender as diferenças do `useMutation` para o `useQuery`, até encontrar o `useLazyQuery`, que se assemelha mais ao método de mutation usado na página de login. Alterei para seguir uma lógica mais fácil de se entender e mais semelhante com a da página inicial.

2022-09-13 13:00 UTC, alanraso commented on pages/users-page.tsx
> +
O problema não é bem o uso de `useQuery` ou `useLazyQuery`, os 2 são semelhantes. O segundo tem um caso de uso mias específico que é quando vc quer esperar algum input do usuário, por exemplo, pra chamar uma query.

2022-09-13 13:03 UTC, alanraso approved these changes

2022-09-13 13:03 UTC, alanraso commented on pages/users-page.tsx
> +  }, []);
Aqui se vc usar apenas o `useQuery`, vc não precisaria desse `useEffect`.

2022-09-13 13:03 UTC, alanraso commented on pages/users-page.tsx
>              )}
Poderia extrair uma função aqui pra deixar mais organizado o código.

2022-09-13 13:03 UTC, alanraso commented on services/apollo.ts
> +import { getValue } from "../persistency";
`getValue` é um nome muito genérico. Aqui talvez fique mais claro algo como `getStorageValue`. O que acha?

2022-09-13 14:46 UTC, merged